<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'ID' => '',
  'Online Pay' => '',
  ' round' => '轮',
  ' rounds' => '轮',
  'Competition List' => '比赛列表',
  'Day 1' => '第一天',
  'Day 2' => '第二天',
  'Day 3' => '第三天',
  'Day 4' => '第四天',
  'Highlight these events:' => '高亮相关项目：',
  'Main Judge' => '主裁判',
  'Wca Competition' => 'WCA比赛',
  'About the Competition' => '关于比赛',
  'Base Entry Fee' => '基础报名费',
  'Check Person' => '报名自动审核',
  'City' => '城市',
  'Click {here} to view the competitors list.' => '点击{here}查看选手列表。',
  'Competition Name' => '比赛名字',
  'Competitors' => '选手',
  'Cubing China' => '粗饼',
  'Cubing China is an information sharing platform for speedsolving competitions, we are not the organizer of such competitions and thus are not responsible for them. Check {link} for our full disclaimer.' => '粗饼网是信息发布平台。我们不是赛事主办方，因此不对比赛具体实施负责。请点击{link}了解更详细的免责声明。',
  'Date' => '日期',
  'Delegate' => '代表',
  'Delegates' => '代表',
  'End Date' => '结束日期',
  'Entry Fee' => '报名费',
  'Events' => '项目',
  'I have read and know the {disclaimer} of Cubing China.' => '我已阅读并知晓粗饼网{disclaimer}。',
  'Information' => '详情',
  'It will be verified automatically after your {paying}.' => '在您{paying}报名费后，系统将自动审核你的报名。',
  'It will be verified by the organisation team soon. Please wait with patience.' => '主办方会尽快审核您的报名，请耐心等待。',
  'Limited Number of Competitor' => '报名人数限制',
  'Links' => '链接',
  'Live' => '直播',
  'Location' => '地点',
  'Main Page' => '详情',
  'Name' => '比赛名称',
  'No competitions now.' => '暂无比赛',
  'Now' => '即日起',
  'Organizers' => '主办方',
  'Person Num' => '限制人数',
  'Province' => '省份',
  'Registration' => '报名',
  'Registration Ending Time' => '报名截止时间',
  'Registration Starting Time' => '报名起始时间',
  'Regulations' => '规则',
  'Results' => '赛果',
  'Schedule' => '赛程',
  'Second Stage All' => '第二阶段包括所有项目',
  'Second Stage Date' => '第二阶段时间',
  'Second Stage Ratio' => '第二阶段倍率',
  'Status' => '状态',
  'The following schedule is proposed by the organizing team. Be aware that the organizing team may change it according to the actual situation. Please pay attention to the announced schedule at the venue to avoid missing your events.' => '此处为比赛主办预计赛程，可能会依据比赛现场情况进行调整，请在比赛日注意现场通知以免耽误您的参赛。',
  'The limited number of competitor has been reached.' => '报名人数已达到上限。',
  'The registration has been closed.' => '比赛报名已截止。',
  'The registration is not open yet.' => '比赛报名尚未开放。',
  'The schedule is to be determined.' => '赛程正在紧张激烈地安排当中。',
  'This competition is recognized as an official World Cube Association competition. Therefore, all competitors should be familiar with the {regulations}.' => '该比赛是世界魔方协会官方认证的比赛，所有选手需要熟知{regulations}。',
  'Travel' => '交通',
  'Travel Info' => '交通信息',
  'Type' => '类型',
  'Venue' => '地点',
  'WCA Competition' => '世界魔方协会认证比赛',
  'WCA Official Page' => 'WCA官方页面',
  'WCA regulations' => 'WCA比赛规则',
  'Wca Competition ID' => 'WCA比赛ID',
  'You don\'t have any certificate.' => '您尚未获得任何证书。',
  'You have not registered for any competition.' => '您尚未报名任何比赛。',
  'Your account is inactive now, please {activate} it before registration.' => '您的账号尚未激活，报名前请先{activate}账号。',
  'Your registration was submitted successfully.' => '您的报名已经成功提交。',
  'disclaimer' => '免责声明',
  'here' => '这里',
);
