<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Lucky Draw'=>'抽奖',
  'Break' => '休息',
  'Award Ceremony' => '颁奖',
  'Opening Intro' => '开场简介',
  '2x2 Cube' => '二阶',
  '4x4 Cube' => '四阶',
  '4x4 blindfolded' => '四盲',
  '5x5 Cube' => '五阶',
  '5x5 blindfolded' => '五盲',
  '6x6 Cube' => '六阶',
  '7x7 Cube' => '七阶',
  'Megaminx' => '五魔方',
  'Pyraminx' => '金字塔',
  'Skewb' => '斜转',
  'Square-1' => 'SQ1',
  'Rubik\'s Clock' => '魔表',
  'Rubik\'s Cube' => '三阶',
  '3x3 blindfolded' => '三盲',
  '3x3 fewest moves' => '最少步',
  '3x3 multi blind' => '多盲',
  '3x3 multi blind old' => '旧多盲',
  '3x3 one-handed' => '单手',
  '3x3 with feet' => '脚拧',
  'Other'=>'其它',
  'Registration'=>'签到',
  'Lunch'=>'午餐',
  'Rubik\'s Magic'=>'八板',
  'Master Magic'=>'十二板',
  'Sport Stacking'=>'竞技叠杯',
  'Funny Event'=>'趣味项目',
);
