<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Export score card' => '导出成绩条',
  'Open' => '',
  'Children' => '少儿组',
  'Close this round' => '结束本轮',
  'Disable User Chatting' => '开启全员禁言',
  'Enable Data Entry' => '开启成绩输入板',
  'Export' => '导出',
  'Females' => '女子组',
  'Finished' => '已结束',
  'Input Panel' => '输入板',
  'Live' => '进行中',
  'New Comers' => '新人组',
  'Online: ' => '在线人数：',
  'Open this round' => '开启本轮',
  'Reset competitors' => '重置选手',
  'Save' => '保存',
  'Show Message on Chat' => '在聊天界面显示新消息',
  'Show Record on Chat' => '在聊天界面显示项目纪录',
  'Show Result on Chat' => '在聊天界面显示更新的成绩',
);
