<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'ID' => '',
  'Weight' => '',
  'name' => '',
  'Content' => '正文',
  'Content Zh' => '中文正文',
  'Date' => '日期',
  'Status' => '状态',
  'Time' => '时间',
  'Title' => '标题',
  'Title Zh' => '中文标题',
  'User' => '发布人',
);
