<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Amount' => '金额',
  'Create Time' => '创建时间',
  'Device Type' => '设备类型',
  'ID' => '',
  'Now Pay Account' => '现在支付账号',
  'Order No' => '订单号',
  'Order Name' => '',
  'Pay Channel' => '支付渠道',
  'Status' => '状态',
  'Sub Type' => '',
  'Type' => '类型',
  'Update Time' => '更新时间',
  'User' => '用户',
);
