<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'ID' => '',
  'If there are sufficient openings from other competitors canceling their registration, your registration will be automatically accepted. If at the end of the registration period your registration has not been accepted, your registration fee will be returned in full.' => '当有足够多的人退赛时，你的报名将会自动通过。若比赛报名结束后你仍在候选列表中，你的报名费将会被全额退款。',
  'No.' => '',
  'User' => '',
  ' CNY' => '元',
  'Date' => '报名时间',
  'Fee (CNY)' => '报名费(元)',
  '<b class="text-danger">Note</b>: A photo is needed to finish your registration.' => '<b class="text-danger">注意</b>：需要提交照片以完成报名。',
  '<b class="text-danger">Note</b>: ID number is collected for registration confirmation and purchase of event insurance by the organizers. Please confirm your information is correct in order to avoid unnecessary inconveniences.' => '<b class="text-danger">备注</b>：组委会收集的陪同人员身份证件信息用于比赛入场身份核实和意外保险的购买。<br>组委会不承担由于选手错误填写证件号码造成的<b class="text-danger">无法入场</b>和<b class="text-danger">投保失败</b>的任何后果。',
  '<b class="text-danger">Note</b>: Please choose your T-shirt size according the below sizes.' => '<b class="text-danger">注意</b>：请根据下方的尺码表选择你的T恤尺码。',
  '<b class="text-danger">Note</b>: Please introduce yourself about your ability in competitions. Don\'t forget to mark the type if you choose other.' => '<b class="text-danger">注意</b>: 请简述你在以往比赛中担任过哪些职务，或你在比赛中擅长的工作类型。选择其他请务必备注想担当的职位（如场控）。',
  '<b>Warning:</b> Once you cancel your registration, you will <b>NOT</b> be a competitor and you cannot register for this competition any longer.' => '<b>警告：</b>一旦退赛，你将失去本次比赛的参赛资格，并<b>无法</b>再次报名该比赛。',
  'Acception Time' => '通过时间',
  'Additional Comments' => '备注',
  'All the information collected will ONLY be used for identity confirmation, insurance and government information backup of the competition. You may choose to delete it after competition or keep it in the database for the use of future competition.' => '所有信息<b>仅用于</b>比赛相关的身份确认、保险办理及公安机关报备等。你可以选择在比赛结束后删除或者留在数据库以便后续比赛使用。',
  'Cancellation Time' => '退赛时间',
  'Competition' => '比赛',
  'Disqualified Events' => '已取消的项目',
  'Do you have any guests joining you at the competition?' => '是否有陪同人员一同前往观看比赛？',
  'Events' => '项目',
  'Fee' => '报名费',
  'Guest Name' => '陪同人员姓名',
  'I have submitted my photo to ACA before and I do not need to change my photo.' => '我曾经给ACA提交过照片，不需更换',
  'I have submitted my photo to ACA before and now I want to change it. / I have not submitted my photo before.' => '我曾经给ACA提交过照片，现在想更换/我没有给ACA提交过照片',
  'Identity Number' => '证件号码',
  'Name' => '姓名',
  'Name of Identity' => '证件名',
  'Only competitors and registered guests may enter the venue. Each competitor may register at most one guest. Guest registration is {fee} RMB. This fee is necessary for venue liability insurance.' => '只接受参赛选手与一名注册观众进场。您需要为该陪同人员缴纳{fee}元费用，此费用组委会将用来购买安全保险以及制作入场凭证等花销。',
  'Paid Fee via Cubing China' => '已付报名费',
  'Payment via Paypal is not accepted automatically. Please wait patiently if you\'ve already paid. We will accept your registration soon.' => '通过Paypal付款不是即时通过的。如果您已付款，请耐心等待，我们会尽快审核。',
  'Pending Events' => '待支付项目',
  'Please choose from the options listed below.' => '请选择：',
  'Please double-confirm your cancellation.' => '请再次确认你的退赛申请。',
  'Please fill your ID number {here} before you register.' => '请先点击{here}填写你的证件号码以便报名。',
  'Registration Cancellation' => '退赛申请',
  'Registration Detail' => '报名详情',
  'Registration Time' => '报名时间',
  'Repeat Identity Number' => '重复证件号码',
  'Reset Payment' => '重置支付订单',
  'Returned Fee to Registrant' => '退回报名费',
  'Self Introduction' => '自我阐述',
  'Staff Type' => '工作人员类型',
  'Status' => '状态',
  'T-shirt Size' => 'T恤尺码',
  'The QR code below is for check-in and relevant matters. You can find it in your registration page at all time. Please show <b class="text-danger">the QR code and the corresponding ID credentials</b> to our staffs for check-in.' => '下方二维码将用于比赛签到及相关事宜，您可以随时在您的报名信息中查看。请在签到时将<b class="text-danger">二维码及相关证件</b>出示给工作人员进行签到。',
  'The refund will be made via the payment method which you have used at the registration.' => '您所退回的费用将通过付款时选择的支付方式退回。',
  'Total Fee' => '报名费',
  'Type of Identity' => '证件类型',
  'Update Registration' => '变更项目',
  'When one of the following occurs, you can reset your order here.' => '出现以下情形之一时，你可以在这里重置支付订单：',
  'You can cancel your registration before {time}.' => '你可以在{time}之前申请退赛。',
  'You have clicked "Pay" above but want to change events now.' => '你已经点击了上方的“支付”但现在想变更项目。',
  'You succeeded in registering for ' => '您已成功报名',
  'Your order has been closed by Alipay due to not paying in time.' => '你的订单因为超时未支付被支付宝关闭；',
  'Your order has been reset successfully.' => '你的订单已重置成功。',
  'Your registration has been accepted.' => '你的报名已经通过审核。',
  'Your registration has been cancelled.' => '你已成功退赛。',
  'Your registration has been disqualified.' => '你的报名因未达到资格线而被取消。',
  'Your registration has been updated successfully.' => '你的报名信息已更新成功。',
  'Your registration has some events in pending status. Please pay for them.' => '您有项目处于待支付状态，请支付。',
  'Your registration is on the waiting list.' => '你当前在候补列表中。',
);
