<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Each competitor may register at most one guest. Guest registration is {fee} RMB. This fee is necessary for venue liability insurance.' => '只接受参赛选手与一名注册观众进场。您需要为该陪同人员缴纳{fee}元费用，此费用组委会将用来购买安全保险以及制作入场凭证等花销。',
  'ID' => '',
  'No.' => '',
  'User' => '',
  'Date' => '报名时间',
  ' CNY' => '元',
  '<b class="text-danger">Note</b>: A photo is needed to finish your registration.' => '<b class="text-danger">注意</b>：需要提交照片以完成报名。',
  '<b class="text-danger">Note</b>: ID number is collected for registration confirmation and purchase of event insurance by the organizers. Please confirm your information is correct in order to avoid unnecessary inconveniences.' => '<b class="text-danger">备注</b>：组委会收集的陪同人员身份证件信息用于比赛入场身份核实和意外保险的购买。<br>组委会不承担由于选手错误填写证件号码造成的<b class="text-danger">无法入场</b>和<b class="text-danger">投保失败</b>的任何后果。',
  'Additional Comments' => '备注',
  'Competition' => '比赛',
  'Entourage' => 'Do you have any guests joining you at the competition?',
  'Events' => '项目',
  'Fee' => '报名费',
  'Fee (CNY)' => '报名费(元)',
  'I have submitted my photo to ACA before and I do not need to change my photo.' => '我曾经给ACA提交过照片，不需更换',
  'I have submitted my photo to ACA before and now I want to change it. / I have not submitted my photo before.' => '我曾经给ACA提交过照片，现在想更换/我没有给ACA提交过照片',
  'Identity Number' => '证件号码',
  'Name' => '姓名',
  'Name of Identity' => '证件名',
  'Please choose from the options listed below.' => '请选择：',
  'Please fill your ID number {here} before you register.' => '请先点击{here}填写你的证件号码以便报名。',
  'Registration Date' => '报名时间',
  'Repeat Identity Number' => '重复证件号码',
  'Status' => '状态',
  'The QR code below is for check-in and relevant matters. You can find it in your registration page at all time. Please show <b class="text-danger">the QR code and the corresponding ID credentials</b> to our staffs for check-in.' => '下方二维码将用于比赛签到及相关事宜，您可以随时在您的报名信息中查看。请在签到时将<b class="text-danger">二维码及相关证件</b>出示给工作人员进行签到。',
  'Total Fee' => '报名费',
  'Type of Identity' => '证件类型',
  'You succeeded in registering for ' => '您已成功报名',
);
