<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'ID' => '',
  'No.' => '',
  'User' => '',
  'Date' => '报名时间',
  ' CNY' => '元',
  '<b class="text-danger">Note</b>: Personal ID is collected for verification and insurance purchasing.<br>The competitors undertake any consequences on <b class="text-danger">failing in registration</b> and <b class="text-danger">insuring</b> due to incorrect personal information.' => '<b class="text-danger">备注</b>：组委会收集选手身份证件信息用以选手比赛签到身份核实和意外保险的购买。<br>组委会不承担由于选手错误填写证件号码造成的<b class="text-danger">无法签到</b>和<b class="text-danger">投保失败</b>造成的任何后果。',
  'Additional Comments' => '备注',
  'Competition' => '比赛',
  'Events' => '项目',
  'Fee' => '报名费',
  'Fee (CNY)' => '报名费(元)',
  'Identity Number' => '证件号码',
  'Name of Identity' => '证件名',
  'Registration Date' => '报名时间',
  'Repeat Identity Number' => '重复证件号码',
  'Status' => '状态',
  'Total Fee' => '报名费',
  'Type of Identity' => '证件类型',
);
