<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Cell Name' => '',
  'ID' => '',
  'Name' => '',
  'Rank' => '',
  'B Final' => 'B组决赛',
  'Combined Final' => '组合制决赛',
  'Combined First' => '组合制初赛',
  'Combined Second' => '组合制复赛',
  'Combined Third' => '组合制半决赛',
  'Combined qualification' => '组合制资格赛',
  'Final' => '决赛',
  'Qualification' => '资格赛',
  'Second' => '复赛',
  'Semi Final' => '半决赛',
  'First' => '初赛',
);
