<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Cumulative' => '',
  'Cut Off' => '',
  'ID' => '',
  'Number' => '',
  'Blue<span class="show-on-full"> Stage</span>' => '蓝色赛台',
  'Classroom' => '教室',
  'Competition' => '比赛',
  'Competitors' => '人数',
  'Cutoff' => '及格线',
  'Day' => '第几天',
  'End Time' => '结束时间',
  'Event' => '项目',
  'Format' => '赛制',
  'Green<span class="show-on-full"> Stage</span>' => '绿色赛台',
  'Group' => '分组',
  'If you reach the time limit during your solve, the judge will stop you and your result will be DNF (see Regulation {A1a4}).' => '如果你某次复原的过程中达到还原时限，裁判会叫停该次复原并记为DNF（参阅规则{A1a4}）。',
  'Long<span class="show-on-full">-time</span> Event<span class="show-on-full"> Stage</span>' => '长项目区',
  'Main<span class="show-on-full"> Stage</span>' => '主赛台',
  'Orange<span class="show-on-full"> Stage</span>' => '橙色赛台',
  'Red<span class="show-on-full"> Stage</span>' => '红色赛台',
  'Round' => '轮次',
  'Side<span class="show-on-full"> Stage</span>' => '分赛台',
  'Stage' => '赛台',
  'Start Time' => '开始时间',
  'The number of advancing competitors will not exceed 75% (see Regulation {9p2}).' => '每轮的晋级人数不会超过上一轮参赛人数的75%（参阅规则{9p2}）。',
  'The result to beat to proceed to the second phase of a combined round (see Regulation {9g}).' => '在组合制轮次中，取得小于及格线的成绩，以获得后面的还原机会（参阅规则{9g}）。',
  'The time limit for 3x3x3 multi-blindfolded is 10 minutes per cube, up to 60 minutes (see Regulation {H1b}).' => '三阶多盲的还原时限是每个魔方10分钟，上限60分钟（参阅规则{H1b}）。',
  'Time Limit' => '还原时限',
  'Up to 60 minutes' => '上限60分',
  'Yellow<span class="show-on-full"> Stage</span>' => '黄色赛台',
);
