<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Cumulative' => '',
  'ID' => '',
  'Number' => '',
  'Blue<span class="show-on-full"> Stage</span>' => '蓝色赛台',
  'Classroom' => '教室',
  'Competition' => '比赛',
  'Competitors' => '人数',
  'Cut Off' => '及格线',
  'Day' => '第几天',
  'End Time' => '结束时间',
  'Event' => '项目',
  'Format' => '赛制',
  'Green<span class="show-on-full"> Stage</span>' => '绿色赛台',
  'Group' => '分组',
  'Long<span class="show-on-full">-time</span> Event<span class="show-on-full"> Stage</span>' => '长项目区',
  'Main<span class="show-on-full"> Stage</span>' => '主赛台',
  'Orange<span class="show-on-full"> Stage</span>' => '橙色赛台',
  'Red<span class="show-on-full"> Stage</span>' => '红色赛台',
  'Round' => '轮次',
  'Side<span class="show-on-full"> Stage</span>' => '分赛台',
  'Stage' => '赛台',
  'Start Time' => '开始时间',
  'Time Limit' => '还原时限',
  'Yellow<span class="show-on-full"> Stage</span>' => '黄色赛台',
);
