<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Classroom' => '教室',
  'ID' => '',
  'Competition' => '比赛',
  'Competitors' => '人数',
  'Cut Off' => '及格线',
  'Day' => '第几天',
  'End Time' => '结束时间',
  'Event' => '项目',
  'Format' => '赛制',
  'Group' => '分组',
  'Long-time Event Stage' => '长项目区',
  'Main Stage' => '主赛台',
  'Round' => '轮次',
  'Side Stage' => '分赛台',
  'Stage' => '赛台',
  'Start Time' => '开始时间',
  'Time Limit' => '还原时限',
);
