<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Appearances in top 100 Chinese competitors\' average results of Rubik\'s Cube' => '中国三速百大平均成绩占席',
  'Appearances in top 100 Chinese competitors\' single results of Rubik\'s Cube' => '中国三速百大单次成绩占席',
  'Best "medal collection" in each event' => '官方赛事分项目累计奖牌榜',
  'Best "medal collection" of all events' => '官方赛事全项目累计奖牌榜',
  'Best podiums in Rubik\'s Cube event' => '中国赛事三阶领奖台成绩榜',
  'Most competitions by one person' => '中国选手的比赛次数排行榜',
  'Most persons in one competition' => '中国赛事的选手人数排行榜',
  'Most solves in one competition' => '单场比赛总复原次数排行榜',
  'Most solves per year' => '全年度累计复原次数排行榜',
  'Oldest standing of current Chinese records in all events' => '中国纪录现保持时间排行榜',
  'Records set by Chinese competitors' => '中国选手创纪录数量排行榜',
  'Records set in Chinese competitions' => '中国赛事创纪录数量排行榜',
  'Sum of 2x2 to 5x5 average ranks' => '二阶至五阶平均综合排行榜',
  'Sum of 2x2 to 5x5 single ranks' => '二阶至五阶单次综合排行榜',
  'Sum of all average ranks' => '官方全项目平均排名总和榜',
  'Sum of all single ranks' => '官方全项目单次综合排行榜',
  'Bronze' => '铜',
  'Competitions' => '比赛次数',
  'Days' => '天数',
  'First' => '冠军',
  'Gold' => '金',
  'Person' => '姓名',
  'Persons' => '人次',
  'Score' => '计分',
  'Second' => '亚军',
  'Silver' => '银',
  'Sum' => '总和',
  'Third' => '季军',
);
