<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Based on {url}, we generate several WCA statistics about Chinese competitions and competitors, which are up-to-date.' => '本页面列出了一系列与官方赛事及中国选手相关的趣味统计，所有的统计数据基本实时更新，源自{url}。',
  'official WCA competition results' => 'WCA赛事的官方成绩',
  'Appearances' => '席位',
  'Appearances in top 100 Chinese average results of Rubik\'s Cube' => '中国三速平均成绩前100占席',
  'Appearances in top 100 Chinese single results of Rubik\'s Cube' => '中国三速单次成绩前100占席',
  'Best "medal collection" in each event' => '官方赛事分项目累计奖牌榜',
  'Best "medal collection" of all events' => '官方赛事全项目累计奖牌榜',
  'Best podiums in Rubik\'s Cube event' => '中国赛事三阶领奖台成绩榜',
  'Bronze' => '铜',
  'Competitions' => '比赛次数',
  'Days' => '天数',
  'First' => '冠军',
  'Gold' => '金',
  'Most competitions by one person' => '中国选手的比赛次数排行榜',
  'Most personal solves' => '个人累积总复原次数排行榜',
  'Most personal solves in each year' => '个人年度总复原次数排行榜',
  'Most personal solves in one competition' => '个人单场总复原次数排行榜',
  'Most persons in one competition' => '中国赛事的选手人数排行榜',
  'Most solves in one competition' => '中国赛事总复原次数排行榜',
  'Oldest standing of current Chinese records in all events' => '中国纪录现保持时间排行榜',
  'Person' => '姓名',
  'Persons' => '人数',
  'Records set by Chinese competitors' => '中国选手创纪录数量排行榜',
  'Records set in Chinese competitions' => '中国赛事创纪录数量排行榜',
  'Score' => '计分',
  'Second' => '亚军',
  'Silver' => '银',
  'Solves/Attempts' => '复原/尝试',
  'Sum' => '总和',
  'Sum of 2x2 to 5x5 average ranks' => '二阶至五阶平均综合排行榜',
  'Sum of 2x2 to 5x5 single ranks' => '二阶至五阶单次综合排行榜',
  'Sum of all average ranks' => '官方全项目平均排名总和榜',
  'Sum of all single ranks' => '官方全项目单次综合排行榜',
  'Third' => '季军',
  'Based on the official WCA competition results, we generated several WCA statistics about Chinese competitions and competitors, which were regularly up-to-date.' => '本页面列出了一系列与官方赛事及中国选手相关的趣味统计，所有的统计数据基本实时更新，源自WCA赛事的官方成绩。',
);
