<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Appearances' => '席位',
  'Appearances in top 100 Chinese average results of Rubik\'s Cube' => '中国三速平均成绩前100占席',
  'Appearances in top 100 Chinese single results of Rubik\'s Cube' => '中国三速单次成绩前100占席',
  'Based on {url}, we generate several WCA statistics about Chinese competitions and competitors, which are up-to-date.' => '本页面列出了一系列与官方赛事及中国选手相关的趣味统计，所有的统计数据基本实时更新，源自{url}。',
  'Best "medal collection" in each event' => '官方赛事分项目累计奖牌榜',
  'Best "medal collection" of all events' => '官方赛事全项目累计奖牌榜',
  'Best podiums' => '中国赛事领奖台成绩榜',
  'Bronze' => '铜',
  'Competitions' => '比赛次数',
  'Days' => '天数',
  'First' => '冠军',
  'Gold' => '金',
  'Most competitions by one person' => '中国选手的比赛次数排行榜',
  'Most personal solves' => '个人累积总复原次数排行榜',
  'Most personal solves in each year' => '个人年度总复原次数排行榜',
  'Most personal solves in one competition' => '个人单场总复原次数排行榜',
  'Most persons in one competition' => '中国赛事的选手人数排行榜',
  'Most solves in one competition' => '中国赛事总复原次数排行榜',
  'Oldest standing of current Chinese records in all events' => '中国纪录现保持时间排行榜',
  'Persons' => '人数',
  'Records set by Chinese competitors' => '中国选手创纪录数量排行榜',
  'Records set in Chinese competitions' => '中国赛事创纪录数量排行榜',
  'Score' => '计分',
  'Second' => '亚军',
  'Silver' => '银',
  'Solves/Attempts' => '复原/尝试',
  'Sum' => '总和',
  'Sum of 2x2 to 5x5 average ranks' => '二阶至五阶平均综合排行榜',
  'Sum of 2x2 to 5x5 single ranks' => '二阶至五阶单次综合排行榜',
  'Sum of all average ranks' => '官方全项目平均综合排行榜',
  'Sum of all single ranks' => '官方全项目单次综合排行榜',
  'Sum of country average ranks' => '各国全项目平均综合排行榜',
  'Sum of country single ranks' => '各国全项目单次综合排行榜',
  'Third' => '季军',
  'official WCA competition results' => 'WCA赛事的官方成绩',
  'Based on the official WCA competition results, we generated several WCA statistics about Chinese competitions and competitors, which were regularly up-to-date.' => '本页面列出了一系列与官方赛事及中国选手相关的趣味统计，所有的统计数据基本实时更新，源自WCA赛事的官方成绩。',
  'Global personal rankings in each official event are listed, based on the the official WCA rankings.' => '本页面列出了各国选手在所有WCA项目的个人排名，所有的排名成绩源自WCA赛事的官方排名。',
  'Global personal rankings in each official event are listed, based on the {url}.' => '本页面列出了各国选手在所有WCA项目的个人排名，所有的排名成绩源自{url}。',
  'Generated on {time}.' => '生成于{time}。',
  'Medal Collection' => '奖牌榜',
  'Most Personal Solves' => '复原榜',
  'Person' => '姓名',
  'Rank' => '排名',
  'Sum of Country Ranks' => '各国综合排行榜',
  'Sum of Ranks' => '排名总和',
  'Best Podiums' => '领奖台成绩榜',
  'We generate several WCA statistics about Chinese competitions and competitors, based on {url}.' => '本页面列出了与官方赛事及中国选手相关的趣味统计，所有的统计数据源自{url}。',
  'Welcome to the Cubing China results page, where you can find the Chinese personal rankings, official records, and fun statistics.' => '欢迎浏览粗饼网的官方成绩页面！你可以在此查看中国魔方选手的个人排名、官方纪录与趣味统计等信息。',
  'Regional records are displayed on the page, based on the official WCA records.' => '本页面列出了所有WCA项目的各地区纪录，所有的成绩纪录源自WCA赛事的官方纪录。',
  'Regional records are displayed on the page, based on the {url}.' => '本页面列出了所有WCA项目的各地区纪录，所有的成绩纪录源自{url}。',
  'official WCA rankings' => 'WCA赛事的官方排名',
  'official WCA records' => 'WCA赛事的官方纪录',
  'official WCA statistics' => 'WCA赛事的官方成绩',
);
