<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Improvements of Average' => '平均成绩提升',
  'Improvements of Single' => '单次成绩提升',
  ' {cuber} was the only one who accompanied the whole {competitions} competitions.' => '{cuber}是唯一一个共同比完所有{competitions}场比赛的。',
  ', {moreThanOne} of them competed with {genderPronoun3} more than once' => '，其中{moreThanOne}个和{genderPronoun3}一起比过两次或以上',
  'In China, {genderPronoun} visited {cities} cit{ies} while competing.' => '在比赛过程中，{genderPronoun}游览了{cities}个中国城市。',
  'In the past year ({year}), {personName} competed in {competitions} competition{cs} and {rounds} round{rs} across {events} event{es}.' => '在过去的一年（{year}）里，{personName}参加了{competitions}场比赛，上场{rounds}个轮次，包括{events}个项目。',
  'all of them were {type}s' => '都是{type}',
  'both were {type}s' => '都是{type}',
  'her' => '她的',
  'including {n1} {type1}{s1} and {n2} {type2}{s2}' => '包括{n1}个{type1}和{n2}个{type2}',
  'including {n1} {type1}{s1}, {n2} {type2}{s2}, and {n3} {type3}{s3}' => '包括{n1}个{type1}、{n2}个{type2}和{n3}个{type3}',
  'which was a {type}' => '是一个{type}',
  '{genderPronoun} attempted {attempt} solves and completed {solve}.' => '{genderPronoun}尝试了{attempt}次复原，成功了{solve}次。',
  '{genderPronoun} broke {genderPronoun2} personal best {total} times, including {best} single{bs} and {average} average{as}.' => '{genderPronoun}打破了{genderPronoun2}个人最好成绩{total}次，其中单次{best}次、平均{average}次。',
  '{genderPronoun} broke {record} record{rs}, {recordsDetail}.' => '{genderPronoun}打破了{record}次纪录，{recordsDetail}。',
  '{genderPronoun} has been on the podium {medal} times, {medalsDetail}.' => '{genderPronoun}登上领奖台{medal}次，{medalsDetail}。',
  '{genderPronoun} met {cubers} cubers{moreThanOne}.{onlyOne}' => '{cubers}个魔友与{genderPronoun}同台竞技过{moreThanOne}。{onlyOne}',
  '{genderPronoun} was very lazy so that nothing left.' => '这个人很懒，什么也没有留下。',
);
