<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'All the information collected will ONLY be used for identity confirmation, insurance and government information backup of the competition.' => '所有信息<b>仅用于</b>比赛相关的身份确认、保险办理及公安机关报备等。',
  'Create Time' => '',
  'Description' => '',
  'Description Zh' => '',
  'Fee' => '',
  'ID' => '',
  'Name' => '入场券种类',
  'Name Zh' => '',
  'Number' => '',
  'Purchase Deadline' => '购买截止日期',
  'Status' => '',
  'Type' => '',
  'Update Time' => '',
);
