<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Bind successfully.' => '绑定成功！',
  'Bind this account' => '绑定当前微信帐号',
  'Current Wechat user has been bound to another user.' => '当前帐号已被绑定至另一个用户。',
  'ID' => '',
  'Password' => '',
  'Please open this page in Wechat. You can scan the following QR.' => '请在微信中打开本页。你可以扫描下面的二维码以快速打开。',
  'Unbind successfully.' => '解绑成功',
  'Unbind this account' => '解绑当前微信帐号',
  'You already bound an account.' => '你已经绑定过微信帐号了。',
  'You haven\'t bound an account.' => '你尚未绑定微信帐号。',
  'Avatar' => '头像',
  'Birthday' => '生日',
  'City' => '城市',
  'Email' => '邮箱',
  'Gender' => '性别',
  'Identity' => '身份',
  'Local Name' => '中文名',
  'Mobile' => '手机号',
  'Name' => '英文名',
  'Province' => '省份',
  'Reg Ip' => '注册IP',
  'Reg Time' => '注册时间',
  'Region' => '地区',
  'Role' => '角色',
  'Status' => '状态',
  'Wcaid' => 'WCA ID',
);
