<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'ID' => '',
  'The schedule is to be determined.' => '賽程正在緊張激烈地安排當中。',
  ' round' => '輪',
  ' rounds' => '輪',
  'Competition List' => '比賽列表',
  'Day 1' => '第一天',
  'Day 2' => '第二天',
  'Day 3' => '第三天',
  'Day 4' => '第四天',
  'Highlight these events:' => '高亮相關項目：',
  'Wca Competition' => 'WCA比賽',
  'About the Competition' => '關於比賽',
  'Alipay Url' => '支付寶鏈接',
  'Base Entry Fee' => '基礎報名費',
  'Check Person' => '報名自動審核',
  'City' => '城市',
  'Click {here} to view the competitors list.' => '點擊{here}查看選手列表。',
  'Competition Name' => '比賽名字',
  'Competitors' => '參賽選手',
  'Cubing China' => '粗餅·中國',
  'Date' => '日期',
  'Delegates' => '代表',
  'End Date' => '結束日期',
  'Entry Fee' => '基礎報名費',
  'Events' => '項目',
  'Information' => '詳情',
  'It will be verified by the organisation team soon. Please wait with patience.' => '主辦方會儘快審核您的報名，請耐心等待。',
  'Location' => '地點',
  'Main Page' => '基本信息',
  'Name' => '姓名',
  'No competitions now.' => '暫無比賽',
  'Organizers' => '主辦方',
  'Person Num' => '限制人數',
  'Province' => '省份',
  'Registration' => '在線報名',
  'Registration Ending Time' => '截止報名時間',
  'Regulations' => '比賽規則',
  'Schedule' => '賽程安排',
  'Status' => '狀態',
  'The registration has been closed.' => '比賽報名已截止。',
  'This competition is recognized as an official World Cube Association competition. Therefore, all competitors should be familiar with the {regulations}.' => '該比賽是世界魔方協會官方認證的比賽，所有選手需要熟知{regulations}。',
  'Travel' => '交通信息',
  'Travel Info' => '交通信息',
  'Type' => '類型',
  'Venue' => '地點',
  'WCA Competition' => '世界魔方協會認證比賽',
  'WCA Official Page' => 'WCA官方頁面',
  'WCA regulations' => 'WCA比賽規則',
  'Wca Competition ID' => 'WCA比賽ID',
  'You have not registered for any competition.' => '您尚未報名任何比賽。',
  'Your account is inactive now, please {activate} it before registration.' => '您的賬號尚未激活，報名前請先{activate}賬號。',
  'Your registration was submitted successfully.' => '您的報名已經成功提交。',
);
