<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'TBA' => '待定',
  'JAN' => '一',
  'FEB' => '二',
  'MAR' => '三',
  'APR' => '四',
  'MAY' => '五',
  'JUN' => '六',
  'JUL' => '七',
  'AUG' => '八',
  'SEP' => '九',
  'OCT' => '十',
  'NOV' => '十一',
  'DEC' => '十二',
);
