<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Lucky Draw'=>'抽獎',
  'Break' => '休息',
  'Award Ceremony' => '頒獎',
  'Opening Intro' => '開場簡介',
  '2x2x2 Cube' => '2x2x2方塊',
  '4x4x4 Cube' => '4x4x4方塊',
  '4x4x4 Blindfolded' => '4x4x4盲解',
  '5x5x5 Cube' => '5x5x5方塊',
  '5x5x5 Blindfolded' => '5x5x5盲解',
  '6x6x6 Cube' => '6x6x6方塊',
  '7x7x7 Cube' => '7x7x7方塊',
  'Megaminx' => 'Megaminx',
  'Pyraminx' => '金字塔',
  'Skewb' => 'Skewb',
  'Square-1' => 'Square-1',
  'Clock' => '魔錶Clock',
  '3x3x3 Cube' => '3x3x3方塊',
  '3x3x3 Blindfolded' => '3x3x3盲解',
  '3x3x3 Fewest Moves' => '最少步數解',
  '3x3x3 Multi-Blind' => '3x3x3多顆盲解',
  '3x3x3 Cube: Multi blind old style' => '舊制3x3x3多顆盲解',
  '3x3x3 One-Handed' => '單手解',
  '3x3x3 With Feet' => '腳解',
  'Other'=>'其它',
  'Registration'=>'簽到',
  'Lunch'=>'午餐',
  'Magic'=>'八板',
  'Master Magic'=>'十二板',
  'Sport Stacking'=>'競技疊杯',
  'Funny Event'=>'趣味項目',
  '3x3x3 Multi-Blind Puzzle Submission'=>'3x3x3多顆盲解提交方塊',
  '3x3x3 Blindfolded Check-in'=>'三盲檢錄',
  '4x4x4 Blindfolded Check-in'=>'四盲檢錄',
  '5x5x5 Blindfolded Check-in'=>'五盲檢錄',
);
