<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Open' => '',
  'U10' => '',
  'U12' => '',
  'U8' => '',
  ' ({round})' => '（{round}）',
  'Children' => '少兒組',
  'Close this round' => '結束本輪',
  'Disable User Chatting' => '開啟全員禁言',
  'Enable Data Entry' => '開啟成績輸入板',
  'Export' => '導出',
  'Export score card' => '導出成績條',
  'Females' => '女子組',
  'Finished' => '已結束',
  'Input Panel' => '輸入板',
  'Live' => '進行中',
  'New Comers' => '新人組',
  'Online: ' => '在線人數：',
  'Open this round' => '開啟本輪',
  'Reset competitors' => '重置選手',
  'Save' => '保存',
  'Show Message on Chat' => '在聊天界面顯示新消息',
  'Show Record on Chat' => '在聊天界面顯示項目紀錄',
  'Show Result on Chat' => '在聊天界面顯示更新的成績',
);
