<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Open' => '',
  'Show Message on Chat' => '在聊天界面顯示新消息',
  'Enable Data Entry' => '開啟成績輸入板',
  'Finished' => '已結束',
  'Input Panel' => '輸入板',
  'Live' => '進行中',
  'Save' => '保存',
  'Show Record on Chat' => '在聊天界面顯示項目紀錄',
  'Show Result on Chat' => '在聊天界面顯示更新的成績',
);
