<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Have you successfully paid?' => '是否成功付款？',
  'ID' => '',
  'Sub Type' => '',
  'Now Pay Account' => '現在支付賬號',
  'Alipay' => '支付寶',
  'Amount' => '金額',
  'Channel' => '渠道',
  'Create Time' => '創建時間',
  'Device Type' => '設備類型',
  'Not yet paid' => '支付失敗',
  'Order Name' => '訂單名',
  'Order No' => '訂單號',
  'Paid Time' => '支付時間',
  'Pay Account' => '支付賬號',
  'Pay Channel' => '支付渠道',
  'Please scan the QR code to pay with Wechat' => '請使用微信掃描以下二維碼',
  'Status' => '狀態',
  'Successfully paid' => '支付成功',
  'Trade No' => '渠道訂單號',
  'Type' => '類型',
  'Update Time' => '更新時間',
  'User' => '用戶',
  'Wechat' => '微信',
  'You are being redirected to {channel} in a few seconds.' => '正在為你跳轉至{channel}支付。',
);
