<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Channel' => '渠道',
  'ID' => '',
  'Order Name' => '',
  'Pay Account' => '支付賬號',
  'Sub Type' => '',
  'Trade No' => '渠道訂單號',
  'Now Pay Account' => '現在支付賬號',
  'Amount' => '金額',
  'Create Time' => '創建時間',
  'Device Type' => '設備類型',
  'Order No' => '訂單號',
  'Pay Channel' => '支付渠道',
  'Status' => '狀態',
  'Type' => '類型',
  'Update Time' => '更新時間',
  'User' => '用戶',
);
