<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Guest Name' => '陪同人員姓名',
  'ID' => '',
  'No.' => '',
  'User' => '',
  'Date' => '報名時間',
  ' CNY' => '元',
  '<b class="text-danger">Note</b>: A photo is needed to finish your registration.' => '<b class="text-danger">注意</b>：需要提交照片以完成報名。',
  '<b class="text-danger">Note</b>: ID number is collected for registration confirmation and purchase of event insurance by the organizers. Please confirm your information is correct in order to avoid unnecessary inconveniences.' => '<b class="text-danger">備注</b>：組委會收集的陪同人員身份證件信息用於比賽入場身份核實和意外保險的購買。<br>組委會不承擔由於選手錯誤填寫證件號碼造成的<b class="text-danger">無法入場</b>和<b class="text-danger">投保失敗</b>的任何後果。',
  'Acception Time' => '通過時間',
  'Additional Comments' => '備注',
  'Competition' => '比賽',
  'Do you have any guests joining you at the competition?' => '是否有陪同人員一同前往觀看比賽？',
  'Events' => '項目',
  'Fee' => '報名費',
  'Fee (CNY)' => '報名費(元)',
  'I have submitted my photo to ACA before and I do not need to change my photo.' => '我曾經給ACA提交過照片，不需更換',
  'I have submitted my photo to ACA before and now I want to change it. / I have not submitted my photo before.' => '我曾經給ACA提交過照片，現在想更換/我沒有給ACA提交過照片',
  'Identity Number' => '證件號碼',
  'Name' => '姓名',
  'Name of Identity' => '證件名',
  'Only competitors and registered guests may enter the venue. Each competitor may register at most one guest. Guest registration is {fee} RMB. This fee is necessary for venue liability insurance.' => '只接受參賽選手與一名注冊觀眾進場。您需要為該陪同人員繳納{fee}元費用，此費用組委會將用來購買安全保險以及制作入場憑證等花銷。',
  'Please choose from the options listed below.' => '請選擇：',
  'Please fill your ID number {here} before you register.' => '請先點擊{here}填寫你的證件號碼以便報名。',
  'Registration Time' => '報名時間',
  'Repeat Identity Number' => '重復證件號碼',
  'Status' => '狀態',
  'The QR code below is for check-in and relevant matters. You can find it in your registration page at all time. Please show <b class="text-danger">the QR code and the corresponding ID credentials</b> to our staffs for check-in.' => '下方二維碼將用於比賽簽到及相關事宜，您可以隨時在您的報名信息中查看。請在簽到時將<b class="text-danger">二維碼及相關證件</b>出示給工作人員進行簽到。',
  'Total Fee' => '報名費',
  'Type of Identity' => '證件類型',
  'You succeeded in registering for ' => '您已成功報名',
);
