<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'ID' => '',
  'No.' => '',
  'User' => '',
  ' CNY' => '元',
  'Date' => '報名時間',
  'Fee (CNY)' => '報名費(元)',
  '<b class="text-danger">Note</b>: A photo is needed to finish your registration.' => '<b class="text-danger">注意</b>：需要提交照片以完成報名。',
  '<b class="text-danger">Note</b>: ID number is collected for registration confirmation and purchase of event insurance by the organizers. Please confirm your information is correct in order to avoid unnecessary inconveniences.' => '<b class="text-danger">備注</b>：組委會收集的陪同人員身份證件信息用於比賽入場身份核實和意外保險的購買。<br>組委會不承擔由於選手錯誤填寫證件號碼造成的<b class="text-danger">無法入場</b>和<b class="text-danger">投保失敗</b>的任何後果。',
  '<b class="text-danger">Note</b>: Please choose your T-shirt size according the below sizes.' => '<b class="text-danger">注意</b>：請根據下方的尺碼表選擇你的T恤尺碼。',
  '<b class="text-danger">Note</b>: Please introduce yourself about your ability in competitions. Don\'t forget to mark the type if you choose other.' => '<b class="text-danger">注意</b>: 請簡述你在以往比賽中擔任過哪些職務，或你在比賽中擅長的工作類型。選擇其他請務必備注想擔當的職位（如場控）。',
  '<b>Warning:</b> Once you cancel your registration, you will <b>NOT</b> be a competitor and you cannot register for this competition any longer.' => '<b>警告：</b>一旦退賽，你將失去本次比賽的參賽資格，並<b>無法</b>再次報名該比賽。',
  'Acception Time' => '通過時間',
  'Additional Comments' => '備注',
  'All the information collected will ONLY be used for identity confirmation, insurance and government information backup of the competition. You may choose to delete it after competition or keep it in the database for the use of future competition.' => '所有信息<b>僅用於</b>比賽相關的身份確認、保險辦理及公安機關報備等。你可以選擇在比賽結束後刪除或者留在數據庫以便後續比賽使用。',
  'Cancellation Time' => '退賽時間',
  'Competition' => '比賽',
  'Do you have any guests joining you at the competition?' => '是否有陪同人員一同前往觀看比賽？',
  'Events' => '項目',
  'Fee' => '報名費',
  'Guest Name' => '陪同人員姓名',
  'I have submitted my photo to ACA before and I do not need to change my photo.' => '我曾經給ACA提交過照片，不需更換',
  'I have submitted my photo to ACA before and now I want to change it. / I have not submitted my photo before.' => '我曾經給ACA提交過照片，現在想更換/我沒有給ACA提交過照片',
  'Identity Number' => '證件號碼',
  'Name' => '姓名',
  'Name of Identity' => '證件名',
  'Only competitors and registered guests may enter the venue. Each competitor may register at most one guest. Guest registration is {fee} RMB. This fee is necessary for venue liability insurance.' => '只接受參賽選手與一名注冊觀眾進場。您需要為該陪同人員繳納{fee}元費用，此費用組委會將用來購買安全保險以及制作入場憑證等花銷。',
  'Paid Fee via Cubing China' => '已付報名費',
  'Payment via Paypal is not accepted automatically. Please wait patiently if you\'ve already paid. We will accept your registration soon.' => '通過Paypal付款不是即時通過的。如果您已付款，請耐心等待，我們會盡快審核。',
  'Pending Events' => '待支付項目',
  'Please choose from the options listed below.' => '請選擇：',
  'Please double-confirm your cancellation.' => '請再次確認你的退賽申請。',
  'Please fill your ID number {here} before you register.' => '請先點擊{here}填寫你的證件號碼以便報名。',
  'Registration Cancellation' => '退賽申請',
  'Registration Detail' => '報名詳情',
  'Registration Time' => '報名時間',
  'Repeat Identity Number' => '重復證件號碼',
  'Reset Payment' => '重置支付訂單',
  'Returned Fee to Registrant' => '退回報名費',
  'Self Introduction' => '自我闡述',
  'Staff Type' => '工作人員類型',
  'Status' => '狀態',
  'T-shirt Size' => 'T恤尺碼',
  'The QR code below is for check-in and relevant matters. You can find it in your registration page at all time. Please show <b class="text-danger">the QR code and the corresponding ID credentials</b> to our staffs for check-in.' => '下方二維碼將用於比賽簽到及相關事宜，您可以隨時在您的報名信息中查看。請在簽到時將<b class="text-danger">二維碼及相關證件</b>出示給工作人員進行簽到。',
  'The refund will be made via the payment method which you have used at the registration.' => '您所退回的費用將通過付款時選擇的支付方式退回。',
  'Total Fee' => '報名費',
  'Type of Identity' => '證件類型',
  'Update Registration' => '變更項目',
  'When one of the following occurs, you can reset your order here.' => '出現以下情形之一時，你可以在這里重置支付訂單：',
  'You can cancel your registration before {time}.' => '你可以在{time}之前申請退賽。',
  'You have clicked "Pay" above but want to change events now.' => '你已經點擊了上方的“支付”但現在想變更項目。',
  'You succeeded in registering for ' => '您已成功報名',
  'Your order has been closed by Alipay due to not paying in time.' => '你的訂單因為超時未支付被支付寶關閉；',
  'Your order has been reset successfully.' => '你的訂單已重置成功。',
  'Your registration has been accepted.' => '你的報名已經通過審核。',
  'Your registration has been cancelled.' => '你已成功退賽。',
  'Your registration has been disqualified.' => '你的報名因未達到資格線而被取消。',
  'Your registration has been updated successfully.' => '你的報名信息已更新成功。',
  'Your registration has some events in pending status. Please pay for them.' => '您有項目處於待支付狀態，請支付。',
  'Your registration is on the waiting list. There are {count} people on the list ahead of you.' => '你當前在候補列表中，前面有{count}個在等待。',
);
