<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'ID' => '',
  'No.' => '',
  'User' => '',
  'Date' => '報名時間',
  ' CNY' => '元',
  '<b class="text-danger">Note</b>: ID number is collected for registration confirmation and purchase of event insurance by the organizers. Please confirm your information is correct in order to avoid unnecessary inconveniences.' => '<b class="text-danger">備注</b>：組委會收集選手身份證件信息用以選手比賽簽到身份核實和意外保險的購買。<br>組委會不承擔由於選手錯誤填寫證件號碼造成的<b class="text-danger">無法簽到</b>和<b class="text-danger">投保失敗</b>的任何後果。<br>如果您提供的身份證件為個人身份證，請注意身份證上的出生日期必須與您在粗餅網注冊的信息一致，否則會提示輸入錯誤。需要修改生日信息，請聯系admin@cubingchina.com。',
  'Additional Comments' => '備注',
  'Competition' => '比賽',
  'Events' => '項目',
  'Fee' => '報名費',
  'Fee (CNY)' => '報名費(元)',
  'Identity Number' => '證件號碼',
  'Name of Identity' => '證件名',
  'Registration Date' => '報名時間',
  'Repeat Identity Number' => '重復證件號碼',
  'Status' => '狀態',
  'The QR code below is for check-in and relevant matters. You can find it in your registration page at all time. Please show <b class="text-danger">the QR code and the corresponding ID credentials</b> to our staffs for check-in.' => '下方二維碼將用於比賽簽到及相關事宜，您可以隨時在您的報名信息中查看。請在簽到時將<b class="text-danger">二維碼及相關證件</b>出示給工作人員進行簽到。',
  'Total Fee' => '報名費',
  'Type of Identity' => '證件類型',
  'You succeeded in registering for ' => '您已成功報名',
);
