<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Cell Name' => '',
  'ID' => '',
  'Name' => '',
  'Rank' => '',
  'Combined Final' => '組合制決賽',
  'Combined First' => '組合制初賽',
  'Combined Second' => '組合制複賽',
  'Combined Third' => '組合制半決賽',
  'Final' => '決賽',
  'First' => '初賽',
  'Second' => '複賽',
  'Semi Final' => '半決賽',
);
