<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Classroom' => '教室',
  'ID' => '',
  'Competition' => '比賽',
  'Competitors' => '人數',
  'Cut Off' => '及格線',
  'Day' => '第幾天',
  'End Time' => '結束時間',
  'Event' => '項目',
  'Format' => '賽制',
  'Group' => '分組',
  'Long-time Event Stage' => '長項目區',
  'Main Stage' => '主賽台',
  'Round' => '輪次',
  'Side Stage' => '分賽台',
  'Stage' => '賽台',
  'Start Time' => '開始時間',
  'Time Limit' => '還原時限',
);
