<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Cumulative' => '',
  'ID' => '',
  'If you reach the time limit during your solve, the judge will stop you and your result will be DNF (see Regulation {A1a4}).' => '如果你某次復原的過程中超過還原時限，裁判會叫停該次復原並記為DNF（參閱規則{A1a4}）。',
  'Number' => '',
  'The number of advanced competitors will not exceed 75% (see Regulation {9p2}).' => '每輪的晉級人數不會超過上一輪參賽人數的75%（參閱規則{9p2}）。',
  'The result to beat to proceed to the second phase of a combined round (see Regulation {9g}).' => '在組合制輪次中，達到及格線以獲得後面的還原機會（參閱規則{9g}）。',
  'The time limit for 3x3x3 multi-blindfolded is 10 minutes per cube, up to 60 minutes (see Regulation {H1b}).' => '三階多盲的還原時限是每個魔方10分鍾，上限60分鍾（參閱規則{H1b}）。',
  'Up to 60 minutes' => '上限60分',
  'Blue<span class="show-on-full"> Stage</span>' => '藍色賽台',
  'Classroom' => '教室',
  'Competition' => '比賽',
  'Competitors' => '人數',
  'Cutoff' => '及格線',
  'Day' => '第幾天',
  'End Time' => '結束時間',
  'Event' => '項目',
  'Format' => '賽制',
  'Green<span class="show-on-full"> Stage</span>' => '綠色賽台',
  'Group' => '分組',
  'Long<span class="show-on-full">-time</span> Event<span class="show-on-full"> Stage</span>' => '長項目區',
  'Main<span class="show-on-full"> Stage</span>' => '主賽台',
  'Orange<span class="show-on-full"> Stage</span>' => '橙色賽台',
  'Red<span class="show-on-full"> Stage</span>' => '紅色賽台',
  'Round' => '輪次',
  'Side<span class="show-on-full"> Stage</span>' => '分賽台',
  'Stage' => '賽台',
  'Start Time' => '開始時間',
  'Time Limit' => '還原時限',
  'Yellow<span class="show-on-full"> Stage</span>' => '黃色賽台',
);
