<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Appearances in top 100 Chinese competitors\' average results of Rubik\'s Cube' => '中國三速百大平均成績占席',
  'Appearances in top 100 Chinese competitors\' single results of Rubik\'s Cube' => '中國三速百大單次成績占席',
  'Best "medal collection" in each event' => '官方賽事分項目累計獎牌榜',
  'Best "medal collection" of all events' => '官方賽事全項目累計獎牌榜',
  'Best podiums in Rubik\'s Cube event' => '中國賽事三階領獎台成績榜',
  'Most competitions by one person' => '中國選手的比賽次數排行榜',
  'Most persons in one competition' => '中國賽事的選手人數排行榜',
  'Most solves in one competition' => '單場比賽總復原次數排行榜',
  'Most solves per year' => '全年度累計復原次數排行榜',
  'Oldest standing of current Chinese records in all events' => '中國紀錄現保持時間排行榜',
  'Records set by Chinese competitors' => '中國選手創紀錄數量排行榜',
  'Records set in Chinese competitions' => '中國賽事創紀錄數量排行榜',
  'Sum of 2x2 to 5x5 average ranks' => '二階至五階平均綜合排行榜',
  'Sum of 2x2 to 5x5 single ranks' => '二階至五階單次綜合排行榜',
  'Sum of all average ranks' => '官方全項目平均排名總和榜',
  'Sum of all single ranks' => '官方全項目單次綜合排行榜',
  'Bronze' => '銅',
  'Competitions' => '比賽次數',
  'Days' => '天數',
  'First' => '冠軍',
  'Gold' => '金',
  'Person' => '姓名',
  'Persons' => '人次',
  'Score' => '計分',
  'Second' => '亞軍',
  'Silver' => '銀',
  'Sum' => '總和',
  'Third' => '季軍',
);
