<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Improvements of Average' => '平均成績提升',
  'Improvements of Single' => '單次成績提升',
  ' {cuber} was the only one who accompanied the whole {competitions} competitions.' => '{cuber}是唯一一個共同比完所有{competitions}場比賽的。',
  ', {moreThanOne} of them competed with {genderPronoun3} more than once' => '，其中{moreThanOne}個和{genderPronoun3}一起比過兩次或以上',
  'In China, {genderPronoun} visited {cities} cit{ies} while competing.' => '在比賽過程中，{genderPronoun}游覽了{cities}個中國城市。',
  'In the past year ({year}), {personName} competed in {competitions} competition{cs} and {rounds} round{rs} across {events} event{es}.' => '在過去的一年（{year}）里，{personName}參加了{competitions}場比賽，上場{rounds}個輪次，包括{events}個項目。',
  'all of them were {type}s' => '都是{type}',
  'both were {type}s' => '都是{type}',
  'her' => '她',
  'including {n1} {type1}{s1} and {n2} {type2}{s2}' => '包括{n1}個{type1}和{n2}個{type2}',
  'including {n1} {type1}{s1}, {n2} {type2}{s2}, and {n3} {type3}{s3}' => '包括{n1}個{type1}、{n2}個{type2}和{n3}個{type3}',
  'which was a {type}' => '是一個{type}',
  '{genderPronoun} attempted {attempt} solves and completed {solve}.' => '{genderPronoun}嘗試了{attempt}次復原，成功了{solve}次。',
  '{genderPronoun} broke {genderPronoun2} personal best {total} times, including {best} single{bs} and {average} average{as}.' => '{genderPronoun}打破了{genderPronoun2}個人最好成績{total}次，其中單次{best}次、平均{average}次。',
  '{genderPronoun} broke {record} record{rs}, {recordsDetail}.' => '{genderPronoun}打破了{record}次紀錄，{recordsDetail}。',
  '{genderPronoun} has been on the podium {medal} times, {medalsDetail}.' => '{genderPronoun}登上領獎台{medal}次，{medalsDetail}。',
  '{genderPronoun} met {cubers} cubers{moreThanOne}.{onlyOne}' => '{cubers}個魔友與{genderPronoun}同台競技過{moreThanOne}。{onlyOne}',
  '{genderPronoun} was very lazy so that nothing left.' => '這個人很懶，什么也沒有留下。',
);
