<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Create Time' => '',
  'Description' => '',
  'Description Zh' => '',
  'Fee' => '',
  'ID' => '',
  'Name Zh' => '',
  'Number' => '',
  'Status' => '',
  'Stock: ' => '庫存：',
  'The ticket you chose is not available.' => '你所選的入場券不能購買。',
  'Type' => '',
  'Update Time' => '',
  'All the information collected will ONLY be used for identity confirmation, insurance and government information backup of the competition.' => '所有信息<b>僅用於</b>比賽相關的身份確認、保險辦理及公安機關報備等。',
  'Name' => '入場券種類',
  'Purchase Deadline' => '購買截止日期',
);
