<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Bind successfully.' => '綁定成功！',
  'Bind this account' => '綁定當前微信帳號',
  'Current Wechat user has been bound to another user.' => '當前帳號已被綁定至另一個用戶。',
  'ID' => '',
  'Password' => '',
  'Please open this page in Wechat. You can scan the following QR.' => '請在微信中打開本頁。你可以掃描下面的二維碼以快速打開。',
  'Unbind successfully.' => '解綁成功',
  'Unbind this account' => '解綁當前微信帳號',
  'You already bound an account.' => '你已經綁定過微信帳號了。',
  'You haven\'t bound an account.' => '你尚未綁定微信帳號。',
  'Avatar' => '頭像',
  'Birthday' => '生日',
  'City' => '城市',
  'Email' => '郵箱',
  'Gender' => '性別',
  'Identity' => '身份',
  'Local Name' => '中文名',
  'Mobile' => '手機號',
  'Name' => '英文名',
  'Province' => '省份',
  'Reg Ip' => '注冊IP',
  'Reg Time' => '注冊時間',
  'Region' => '地區',
  'Role' => '角色',
  'Status' => '狀態',
  'Wcaid' => 'WCA ID',
);
