<?php
return array(
	array(
		'name'=>'World Cube Association',
		'name_zh'=>'世界魔方协会',
		'url'=>'https://www.worldcubeassociation.org/',
		'logo'=>'/f/images/links/WCA.png',
		'description'=>'WCA governs speedcubing competitions for Rubik’s Cube and some other twisty puzzles. It aims at organizing more competitions in more countries with more people and more fun, under fair and equal conditions and in a friendly atmosphere.',
		'description_zh'=>'世界魔方协会是魔方速拧运动的官方管理结构，依照公平的规则，执行公正的管理，它旨在世界范围内举办更多公开的赛事，从而让更多的人享受到魔方速拧的快乐，并号召大家在比赛中友好互助，发挥运动家精神。',
	),
	array(
		'name'=>'World Sport Stacking Association',
		'name_zh'=>'世界竞技叠杯协会',
		'url'=>'http://www.thewssa.com/',
		// 'logo'=>'/f/images/links/WCA.png',
		'description'=>'WSSA promotes the standardization and advancement of sport stacking worldwide. It serves as the governing body for sport stacking rules and regulations and provides a uniform framework for sport stacking events; sanctions sport stacking competitions and records.',
		'description_zh'=>'世界竞技叠杯协会是竞技叠杯运动的官方管理机构，通过制定官方规则、举办专业赛事、管理赛事成绩纪录，来促进该运动的标准化与全球化发展',
	),
	'-',
	array(
		'name'=>'SpeedSolving',
		'name_zh'=>'SpeedSolving',
		'url'=>'http://www.speedsolving.com/',
		'logo'=>'/f/images/links/SS.png',
		'description'=>'The most active international forum and global community on speedcubing.',
		'description_zh'=>'SpeedSolving论坛是国际性的魔方速拧论坛，集中了世界上最专业的魔方玩家，最专业的魔方竞速知识，最新鲜的魔方相关资讯。',
	),
	array(
		'name'=>'MF8 Chinese Cube Club',
		'name_zh'=>'魔方吧•中国魔方俱乐部',
		'url'=>'http://bbs.mf8-china.com/',
		'logo'=>'/f/images/links/MF8.png',
		'description'=>'The earliest Chinese cubing forum dedicated to speedcubing, including miscellaneous materials and professional information in twisty puzzles and other puzzles',
		'description_zh'=>'魔方吧·中国魔方俱乐部是国内成立最早、内容最专业的中文魔方论坛。其中汇集了众多魔方的玩法与高级教程、定期发布魔方专业资讯与魔方赛事消息，同时还涵盖了各种益智游戏与谜题的玩法。',
	),
	array(
		'name'=>'Hong Kong Rubik’s Cube Union',
		'name_zh'=>'好骰同盟',
		'url'=>'http://hkrcu.net/',
		'logo'=>'/f/images/links/HKRCU.png',
		'description'=>'The cubing community in Hong Kong, for news on cubing activities and speedcubing competitions in Hong Kong.',
		'description_zh'=>'好骰同盟是香港的最早最专业的魔方协会，作为香港的官方魔方组织，它通过宣傳和推廣魔方，深入民众对扭這項活動的認識。',
	),
	array(
		'name'=>'CubingTW',
		'name_zh'=>'臺灣魔術方塊社群',
		'url'=>'http://cubing-tw.net/',
		'logo'=>'/f/images/links/CubingTW.png',
		'description'=>'Taiwanese cubing club and forum, for discussing topics regarding twisty puzzles and speedcubing competitions in Taiwan.',
		'description_zh'=>'臺灣魔術方塊社群是台湾新开设的专业魔方社区，其中包括了台湾魔友交流、台湾魔方比赛、台湾魔方产品等信息。',
	),
	'-',
	array(
		'name'=>'csTimer',
		'name_zh'=>'CS魔方计时器',
		'url'=>'http://cstimer.net/timer.php',
		'logo'=>'/f/images/links/cstimer.png',
		'description'=>'The professional timer for speedcubing, csTimer supports scrambles of many types of puzzles include all the WCA official puzzle, and integrated with Xcross and eoline solver, time statistics and other functions. The designer, Shuang Chen, is the member of WCA Scrambler Team.',
		'description_zh'=>'csTimer是专门为魔方爱好者精心设计的一款专业计时软件，是迄今为止功能最全面、界面最友好、使用最便捷的在线网页魔方计时器。其设计者陈霜是世界魔方协会（WCA）魔方打乱程序开发组专员',
	),
);